name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: Publish version
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
      dryRun:
        description: Dry run
        default: true
        type: boolean


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - uses: nodenv/actions/node-version@v2.0.10
        id: nodenv

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}

      - name: restore node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: dry run
        if: github.event.inputs.dryRun == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npx lerna publish ${{ github.event.inputs.version }} --no-git-tag-version --no-push

      - name: publish
        if: github.event.inputs.dryRun != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npx lerna publish ${{ github.event.inputs.version }} --yes
